Description of imagedesc_ch2desc
imagedesc_ch2desc
PURPOSE
Helper, converts descriptor in array format to vector or histogram.
SYNOPSIS
function desc = imagedesc_ch2desc(CHS, ch2params, iscuboid, nch, ninst)
DESCRIPTION
 Helper, converts descriptor in array format to vector or histogram.
 Takes the multiple channel, multiple instance input and creates a descriptor by:
   1) histFlat==-1  stringing out the channels
   2) histFlat== 0  using nchs*ninst 1D-histograms
   3) histFlat== 1  using ninst nch-histograms [SLOW]
 INPUTS
   CHS         - mxn    x  nchs  x  ninst (if image)
               - mxnxt  x  nchs  x  ninst (if cuboid)
   ch2params   - STRUCT with the following fields
           histFLAG    - if -1 string out vector, if 0 1D histograms, 1 3D histograms
           pargmask    - [optional] param to histc_sift (mask_gaussians)
           edges       - [optional] param to histc_sift (histogram edges)
   iscuboid    - should be true if cuboid, 0 otherwise [if 2d patch]
   nch         - must specify number channels, nch [error checking]
   ninst       - must specify number instances, ninst [error checking]
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
desccuboid_APR Cuboid descriptor based on histogrammed brightness values.
desccuboid_FLOW Cuboid descriptor based on histogrammed optical flow.
desccuboid_GRAD Cuboid descriptor based on histogrammed gradient.
descpatch_FB Patch descriptor based on histogrammed filter responses.
descpatch_GRAD Patch descriptor based on histogrammed gradient [Lowe's SIFT descriptor].