Description of imagedesc2clusters
imagedesc2clusters
PURPOSE
Assignment of descriptors to clusters.
SYNOPSIS
function desc2 = imagedesc2clusters(desc, clusters, csigma)
DESCRIPTION
 Assignment of descriptors to clusters.
 For each descriptor desci (1xp vector), assigns desci to the closest cluster in
 clusters.  desc2i is thus a scalar that indicates the cluster membership of desci, or a
 1xnclusters vector which is the result of a soft assign of desc1 to clusters (see
 softmin for more information).
 Note that imagedesc may have already called this function, if so make sure not to call
 it again.
 INPUTS
   desc        - nxp array of n p-dimensional descriptors
                 nxpxr array of n p-dimensional descriptors, r jittered versions of each
   clusters    - nclusters x p array of cluster centers
   csigma      - [optional] soft assign to clusters, see softmin
 OUTPUTS
   desc2       - nxp array of cluster memberships (p==1 if csigma not given)
 See also SOFTMIN
CROSS-REFERENCE INFORMATION
This function calls:
jitter_dist Calculates the minumum distance between two sets of possibly 'jittered' feature vectors.
This function is called by:
imagedesc Runs descriptor on a set of images, optionally jitters, and optionally applies PCA.
recog_clipsdesc Create descriptor of every clip.