Description of imagedesc
imagedesc
PURPOSE
Runs descriptor on a set of images, optionally jitters, and optionally applies PCA.
SYNOPSIS
function desc = imagedesc(I, imdesc, show)
DESCRIPTION
 Runs descriptor on a set of images, optionally jitters, and optionally applies PCA.
 Parameters are passed in w struct imdesc.  Use imagedesc_generate to quickly generate
 this struct.
 If clusters (and optionally csigma) are provided, imagedesc2clusters is applied to each
 resulting desc (giving a new descriptor).  See imagedesc2clusters for more information.
 INPUTS
   I               - 2D or 3D array of images, or 3D or 4D array of cuboids
   imdesc          - struct containing the following fields:
       iscuboid        - specifies whether desc is designed for image or cuboid
       fun_desc        - (fhandle) descriptor to apply to each image or cuboid
       par_desc        - parameters for above descriptor
       par_jitter      - [optional] parameters for jittering images or cuboids
       par_pca         - [optional] parameters for PCA to reduce dim of descriptor
       clusters        - [optional] see imagedesc2clusters
       csigma          - [optional] see imagedesc2clusters
   show            - [optional] figure to use for display (no display if == 0)
 OUTPUTS
   desc        - nxpxr array of n p-dimensional descriptors, r jittered versions of each
               - nxp array if par_jitter is not given or clusters is given
 See also IMAGEDESC_GENERATE, IMAGEDESC_DEMO, IMAGEDESC2CLUSTERS
CROSS-REFERENCE INFORMATION
This function calls:
imagedesc2clusters Assignment of descriptors to clusters.
jitter_dist Calculates the minumum distance between two sets of possibly 'jittered' feature vectors.
This function is called by:
desccuboid_IMDESC Cuboid descriptor based on a concatentation of the types of frames present.
desccuboid_WW Cuboid descriptor that is a combination of 'who' doing 'what'.
imagedesc_demo Demo to show how imagedesc works.
imagedesc_getpca Runs descriptor on a subset of cuboids or images to get PCA coefficients.
featuresLGdesc Applies descriptor to every cuboid of every clip of every set.
featuresSMdesc Applies descriptor to every cuboid of every clip of every set.