Description of imagedesc_demo
imagedesc_demo
PURPOSE
Demo to show how imagedesc works.
SYNOPSIS
This is a script file.
DESCRIPTION
 Demo to show how imagedesc works.
 This is a script, tweak to see how things work.
 See also IMAGEDESC, IMAGEDESC_GENERATE
CROSS-REFERENCE INFORMATION
This function calls:
imagedesc Runs descriptor on a set of images, optionally jitters, and optionally applies PCA.
imagedesc_generate Generate parameters for image or cuboid descriptor.
imagedesc_getpca Runs descriptor on a subset of cuboids or images to get PCA coefficients.
jitter_dist Calculates the minumum distance between two sets of possibly 'jittered' feature vectors.
jitter_kmeans Version of kmeans that allows for jittered vectors.
jitter_rectify Post processing for jitter_kmeans.
This function is called by: