Description of imagedesc_getpca
imagedesc_getpca
PURPOSE
Runs descriptor on a subset of cuboids or images to get PCA coefficients.
SYNOPSIS
function imdesc = imagedesc_getpca(I, imdesc, k, show)
DESCRIPTION
 Runs descriptor on a subset of cuboids or images to get PCA coefficients.
 INPUTS
   I               - 3D array of images or 4D array of cuboids
   imdesc          - descriptor to apply to each image or cuboid
   k               - number of PCA coefficients to use [note: k can be later reduced]
 OUTPUTS
   imdesc          - new imdesc with PCA information
CROSS-REFERENCE INFORMATION
This function calls:
imagedesc Runs descriptor on a set of images, optionally jitters, and optionally applies PCA.
This function is called by:
imagedesc_demo Demo to show how imagedesc works.
featuresLGpca Dimensionality reduction for cuboids descriptors.
featuresSMpca Dimensionality reduction for cuboids descriptors.