Description of imagedesc_generate
imagedesc_generate
PURPOSE
Generate parameters for image or cuboid descriptor.
SYNOPSIS
function imdesc = imagedesc_generate(iscuboid, str_desc, histFLAG, jitterFLAG)
DESCRIPTION
 Generate parameters for image or cuboid descriptor.
 INPUTS
   iscuboid    - 1 for cuboids, 0 for patches
   str_desc    - 'GRAD', 'FB' for images [see descpatch_*.m]
               - 'APR', 'GRAD', 'IMDESC', 'WW', 'FLOW' [see desccuboid_*.m]
   histFLAG    - see imagedesc_ch2desc, also has some additional values [2,3]
   jitterFLAG  - [optional] see jitter_dist, causes everything to be very slow
 See also IMAGEDESC, IMAGEDESC_DEMO, IMAGEDESC_CH2DESC
CROSS-REFERENCE INFORMATION
This function calls:
desccuboid_APR Cuboid descriptor based on histogrammed brightness values.
desccuboid_FLOW Cuboid descriptor based on histogrammed optical flow.
desccuboid_GRAD Cuboid descriptor based on histogrammed gradient.
desccuboid_IMDESC Cuboid descriptor based on a concatentation of the types of frames present.
desccuboid_WW Cuboid descriptor that is a combination of 'who' doing 'what'.
descpatch_FB Patch descriptor based on histogrammed filter responses.
descpatch_GRAD Patch descriptor based on histogrammed gradient [Lowe's SIFT descriptor].
imagedesc_generate Generate parameters for image or cuboid descriptor.
This function is called by:
imagedesc_demo Demo to show how imagedesc works.
imagedesc_generate Generate parameters for image or cuboid descriptor.
recognition_demo Describes all steps of behavior recognition; example for facial expressions.