Description of cuboid_display
cuboid_display
PURPOSE
Fancy cuboid visualization.
SYNOPSIS
function [ V, Imasked ] = cuboid_display(I, cuboids_rs, subs, show)
DESCRIPTION
 Fancy cuboid visualization.
 Extracts cuboids of given size from the array I at specified locations, using
 cuboid_extract.  It then displays a fancy visualiztion of the cuboids.  Only works if I
 is MxN or MxNxK (2 or 3 dimensional data).  Tends to work well only if not too much
 overlap between cuboids (otherwise V is very dark).
 INPUTS
   I               - d dimension array
   cuboids_rs      - the dimensions of the cuboids to find (d x 1)
   subs            - subscricts of max locations (n x d)
   show            - [optional] figure to use for display (no display if == 0)
 OUTPUTS
   V           - color version of I with each cuboid being a different color
   Imasked     - I with everything blocked out except regions belonging to cuboids
 See also CUBOID_EXTRACT, CUBOID_DISPLAY_STV
CROSS-REFERENCE INFORMATION
This function calls:
cuboid_extract Extracts cuboids of given size from the array I at specified locations.
This function is called by:
makemovie_featurelocations Creates visualization of detected feature locations over multiple scales.
stfeatures Interface to spatio-temporal feature detectors.