Description of stfeatures
stfeatures
PURPOSE
Interface to spatio-temporal feature detectors.
SYNOPSIS
function [R,subs,vals,cuboids,V] = stfeatures(I, sigma, tau, periodic, thresh, maxn,overlap_r, shr_spt, shr_tmp, show)
DESCRIPTION
 Interface to spatio-temporal feature detectors.
 Wrapper for stfeatures detectors that first shrinks I and then resizes outputs
 appropriately.  It also applies nonmaximal supression and finds local maxima of detector
 output.
 INPUTS
   I           - 3D uint (or double) array - input video
   sigma       - spatial scale
   tau         - temporal scale
   periodic    - if 1 uses periodic detector else uses harris detector
   thresh      - [optional] abolute threshold for features strength
   maxn        - [optional] maximum number of featrues (alternative to thresh)
   overlap_r   - [optional] controls amount of overlap between cuboids, range: [0,2)
                 (0 -> no overlap, 2 -> minimal restriction on overlap; 1.7 -> default )
   show        - [optional] figure to use for display (no display if == 0)
   shr_spt     - [optional] spatial shrink factor.  Must be integer>1
   tau_spt     - [optional] temporal shrink factor.  Must be integer>1
 OUTPUTS
   R       - detector strength response at each image location
   subs    - detected features locations
   vals    - relative feature strengths
   cuboids - the detected cuboids (size depends on sigma/tau)
   V       - location of responses visualization
 EXAMPLE
   load example;
   [R,subs,vals,cuboids,V] = stfeatures( I, 2, 3, 1, 2e-4, [], 1.85, 2, 1, 1 );
   [R,subs,vals,cuboids,V] = stfeatures( I, 2, 3, 0, eps, [], 1.85, 2, 1, 5 );
 See also STFEATURES_HARRIS, STFEATURES_PERIODIC, NONMAXSUPR_WINDOW
CROSS-REFERENCE INFORMATION
This function calls:
cuboid_display Fancy cuboid visualization.
cuboid_extract Extracts cuboids of given size from the array I at specified locations.
stfeatures_harris Laptev & Lindeberg spatiotemporal feature detector - interface through stfeatures.
stfeatures_periodic Piotr's spatiotemporal feature detector - interface through stfeatures.
This function is called by:
featuresLGdetect Detects features for each set of cuboids using stfeatures.
featuresSMdetect Detects features for each set of cuboids using stfeatures.
stfeatures_allscales Apply spatio-temporal feature detector at a number of scales.
stfeatures_demo Demo of stfeatures on the "oscillating example".