Description of datadir
datadir
PURPOSE
Get location of data; alter file depending on location of dataset.
SYNOPSIS
function dir = datadir(set_ind)
DESCRIPTION
 Get location of data; alter file depending on location of dataset.
 INPUTS
   set_ind     - [optional] set index, value between 0 and nsets-1
 OUTPUTS
   dir         - final directory
 EXAMPLE
   dir = getclipsdir( 'mouse00', 'features' )
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
conv_clips2datasets Converts between representations of behavior (mat -> DATASETS).
conv_clips2movies Converts between representations of behavior (avi -> mat).
conv_datasets2clips Converts between representations of behavior (DATASETS -> mat).
conv_movies2clips Converts between representations of behavior (mat -> avi).
conv_movies2divx Converts between representations of behavior (avi -> compressed avi).
featuresLGconv Convert features to DATASETS format so output is same as after featuresSM.
featuresLGdesc Applies descriptor to every cuboid of every clip of every set.
featuresLGdetect Detects features for each set of cuboids using stfeatures.
featuresLGpca Dimensionality reduction for cuboids descriptors.
recognition_demo Describes all steps of behavior recognition; example for facial expressions.