Description of featuresLGpca
featuresLGpca
PURPOSE
Dimensionality reduction for cuboids descriptors.
SYNOPSIS
function [cubdesc,cuboids] = featuresLGpca(nsets, ncuboids, cubdesc, kpca)
DESCRIPTION
 Dimensionality reduction for cuboids descriptors.
 Assumes feature extraction (FEATURESLGDETECT) has been run.
 See FEATURESSMPCA for more info.
 INPUTS
   nsets       - number of sets
   ncuboids    - number of cuboids to grab per .mat file
   cubdesc     - cuboid descriptor [see imagedesc_getpca]
   kpca        - number of dimensions to reduce data to [see imagedesc_getpca]
 OUTPUTS
   cubdec      - cuboid descriptor with pca info [see imagedesc_getpca]
   cuboids     - sampled cuboids
 See also FEATURESLG, FEATURESSMPCA, FEATURESLGDETECT
CROSS-REFERENCE INFORMATION
This function calls:
imagedesc_getpca Runs descriptor on a subset of cuboids or images to get PCA coefficients.
datadir Get location of data; alter file depending on location of dataset.
This function is called by:
featuresLG Feature detection and description applied to .mat behavior data.