Description of featuresLGdesc
featuresLGdesc
PURPOSE
Applies descriptor to every cuboid of every clip of every set.
SYNOPSIS
function featuresLGdesc(nsets, cubdesc)
DESCRIPTION
 Applies descriptor to every cuboid of every clip of every set.
 Loads each cuboids_[activity].mat, describues cuboids, then saves result to
 features_[activity].mat.  Each original mat file should contain the fields: 'clipname',
 'cliptype', 'cuboids', 'subs', resulting mat file will contain the fields:
 'clipname', 'cliptype', 'subs', 'desc'.
 INPUTS
   nsets       - number of sets
   cubdesc     - cuboid descriptor
 See also FEATURESLG, IMAGEDESC, IMAGEDESC_GENERATE
CROSS-REFERENCE INFORMATION
This function calls:
imagedesc Runs descriptor on a set of images, optionally jitters, and optionally applies PCA.
datadir Get location of data; alter file depending on location of dataset.
This function is called by:
featuresLG Feature detection and description applied to .mat behavior data.