Description of featuresLGdetect
featuresLGdetect
PURPOSE
Detects features for each set of cuboids using stfeatures.
SYNOPSIS
function featuresLGdetect(nsets, cliptypes, par_stfeatures)
DESCRIPTION
 Detects features for each set of cuboids using stfeatures.
    clip_[activity].mat -->  features_[activity].mat
 Loads each clip_[activity].mat, detects features, then saves result to
 cuboids_[activity].mat.  Each original mat file should contain the fields: 'I',
 'clipname' and 'cliptype', the resulting mat file will contain the fields: 'clipname',
 'cliptype', 'cuboids', 'subs'.
 INPUTS
   nsets           - number of sets
   cliptypes       - types of clips (cell of strings)
   par_stfeature   - parameters for feature detection, see stfeatures
 See also FEATURESLG, STFEATURES, FEATURESSMDETECT
CROSS-REFERENCE INFORMATION
This function calls:
datadir Get location of data; alter file depending on location of dataset.
stfeatures Interface to spatio-temporal feature detectors.
This function is called by:
featuresLG Feature detection and description applied to .mat behavior data.