Description of recog_clipsdesc
recog_clipsdesc
PURPOSE
Create descriptor of every clip.
SYNOPSIS
function data = recog_clipsdesc(DATASETS, clusters, csigma)
DESCRIPTION
 Create descriptor of every clip.
 Takes clusters and assigns each cuboid to its type.  Next, the cuboid types are
 histogrammed to create a descriptor for each clip in each dataset.
 INPUTS
   DATASETS    - array of structs, should have the fields:
           .desc       - length N cell vector of cuboid descriptors
           .ncilps     - N: number of clips
   clusters    - cuboid clusters
   csigma      - soft assign see clipdesc
 OUTPUTS
   data        - length N cell vector of (nclips x p) arrays of data
CROSS-REFERENCE INFORMATION
This function calls:
imagedesc2clusters Assignment of descriptors to clusters.
recog_clipdesc Creates a clip descriptor that is simply a histogram of cuboids present.
This function is called by:
recog_test Test the performance of behavior recognition using the cuboid representation.
recog_test_nfold Test the performance of behavior recognition using cross validation.