Description of recog_test
recog_test
PURPOSE
Test the performance of behavior recognition using the cuboid representation.
SYNOPSIS
function [ER,CMS] = recog_test(DATASETS, k, nreps)
DESCRIPTION
 Test the performance of behavior recognition using the cuboid representation.
 Given n sets of data, each containing multiple data instances, we train on 1 set at a
 time, and then test on each of the remaining sets.  Thus there are (n x n) separate
 training/testing scenarios. [Note: to get performance on set i given training on i we
 use cross validation WITHIN the set].   Note that this is not cross validation where
 training occurs on all but (n-1) of the sets and testing on the remaining one, giving a
 total of (n) training/testing scenarios.
 Clustering is performed (using recog_cluster) on cuboids from the single training set.
 Once the clustering is obtained, each cuboid in all the clips in all the sets is
 assigned a type and each clip is converted to a histogram of cuboid types (using
 recog_clipsdesc).  Afterwards standard classification techniques are used to train/test.
 Parameters for clustering and classification can be specified inside this file.
 INPUTS
   DATASETS    - array of structs, should have the fields:
           .IDX        - length N vector of clip types
           .desc       - length N cell vector of cuboid descriptors
           .ncilps     - N: number of clips
   k           - number of clusters
   nreps       - number of repetitions
 OUTPUTS
   ER      - error matricies [nsets x nsets] - averaged over nreps
   CMS     - confusion matricies [nclass x nclass x nsets x nsets] - averaged over nreps
 See also RECOGNITION_DEMO, RECOG_TEST_NFOLD, NFOLDXVAL, RECOG_CLUSTER, RECOG_CLIPSDESC
CROSS-REFERENCE INFORMATION
This function calls:
recog_clipsdesc Create descriptor of every clip.
recog_cluster Clusters all cuboids in DATASETS (based on their descriptions).
This function is called by:
recognition_demo Describes all steps of behavior recognition; example for facial expressions.